#
# Copyright 2018 IBM All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

volumes:
  orderer.bikeshare.com:
  peer0.providerorg.bikeshare.com:
  peer0.userorg.bikeshare.com:
  peer0.repairerorg.bikeshare.com:

networks:
  bsn:
services:
  provider-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-providerorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.providerorg.bikeshare.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/EXPORTER_CA_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.providerorg.bikeshare.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/EXPORTER_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/providerorg.bikeshare.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerProviderOrg
    networks:
      - bsn

  user-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-userorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.userorg.bikeshare.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/IMPORTER_CA_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.userorg.bikeshare.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/IMPORTER_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/userorg.bikeshare.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerUserOrg
    networks:
      - bsn

  repairer-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-repairerorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.repairerorg.bikeshare.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CARRIER_CA_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.repairerorg.bikeshare.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CARRIER_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/repairerorg.bikeshare.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerRepairerOrg
    networks:
      - bsn

  orderer.bikeshare.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bikeshare.com
    container_name: orderer.bikeshare.com
    networks:
      - bsn

  peer0.providerorg.bikeshare.com:
    container_name: peer0.providerorg.bikeshare.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.providerorg.bikeshare.com
    networks:
      - bsn

  peer0.userorg.bikeshare.com:
    container_name: peer0.userorg.bikeshare.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.userorg.bikeshare.com
    networks:
      - bsn

  peer0.repairerorg.bikeshare.com:
    container_name: peer0.repairerorg.bikeshare.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.repairerorg.bikeshare.com
    networks:
      - bsn
