package main

// Object types
const (
	USER				= "USER"
	REPAIRER			= "REPAIRER"
	BIKE				= "BIKE"
	RIDE				= "RIDE"
	ISSUE				= "ISSUE"
	REPAIR				= "REPAIR"
)

// User state values
const (
	USER_FREE			= "USER_FREE"
	USER_IN_RIDE		= "USER_IN_RIDE"
)

// Bike state values
const (
	BIKE_AVAILABLE		= "BIKE_AVAILABLE"
	BIKE_IN_USE			= "BIKE_IN_USE"
	BIKE_TO_REPAIR		= "BIKE_TO_REPAIR"
	BIKE_REPAIRING		= "BIKE_REPAIRING"
	BIKE_REPAIRED		= "BIKE_REPAIRED"
	BIKE_DISCARDED		= "BIKE_DISCARDED"
)

// Ride state values
const (
	RIDE_ONGOING		= "RIDE_ONGOING"
	RIDE_COMPLETED		= "RIDE_COMPLETED"
	RIDE_ISSUE_OPEN		= "RIDE_ISSUE_OPEN"
	RIDE_ISSUE_CLOSED	= "RIDE_ISSUE_CLOSED"
)

// Issue state values
const (
	ISSUE_OPEN			= "ISSUE_OPEN"
	ISSUE_CLOSED		= "ISSUE_CLOSED"
)

// Repair state values
const (
	REPAIR_REQUESTED	= "REPAIR_REQUESTED"
	REPAIR_ACCEPTED		= "REPAIR_ACCEPTED"
	REPAIR_REJECTED		= "REPAIR_REJECTED"
	REPAIR_COMPLETED	= "REPAIR_COMPLETED"
)
