package main

// Object types
const (
	BIKE			= "BIKE"
	RIDE			= "RIDE"
	ISSUE			= "ISSUE"
	REPAIR			= "REPAIR"
)

// Bike state values
const (
	BIKE_AVAILABLE		= "BIKE_AVAILABLE"
	BIKE_IN_USE			= "BIKE_IN_USE"
	BIKE_REPAIRING		= "BIKE_REPAIRING"
	BIKE_DISCARDED		= "BIKE_DISCARDED"
)

// Ride state values
const (
	RIDE_ONGOING		= "RIDE_ONGOING"
	RIDE_COMPLETED		= "RIDE_COMPLETED"
	RIDE_ISSUE_REPORTED	= "RIDE_ISSUE_REPORTED"
	RIDE_ISSUE_RESOLVED	= "RIDE_ISSUE_RESOLVED"
)

// Issue state values
const (
	ISSUE_OPEN			= "ISSUE_OPEN"
	ISSUE_CLOSED		= "ISSUE_CLOSED"
)

// Repair state values
const (
	REPAIR_REQUESTED	= "REPAIR_REQUESTED"
	REPAIR_ACCEPTED		= "REPAIR_ACCEPTED"
	REPAIR_REJECTED		= "REPAIR_REJECTED"
	REPAIR_COMPLETED	= "REPAIR_COMPLETED"
	REPAIR_CLOSED		= "REPAIR_CLOSED"
)
